---
- name: Update and install dependencies
  apt:
    update_cache: yes
    name:
      - curl
      - ca-certificates
      - tzdata
      - openssh-server
    state: present

- name: Add GitLab repository key
  apt_key:
    url: "{{ Keylink }}"
    state: present

- name: Add GitLab repository
  apt_repository:
    repo: "{{ repo_link }}"
    state: present
    filename: gitlab

- name: Install GitLab CE
  apt:
    name: gitlab-ce
    state: present
    update_cache: yes

- name: Configure GitLab from template
  template:
    src: gitlab.ce.j2
    dest: /etc/gitlab/gitlab.rb
    mode: 0644
    owner: root
    group: root

- name: Reconfigure GitLab
  command: gitlab-ctl reconfigure
  notify: Restart GitLab


